default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8mb4
  database: NCKUOPEN_test
  host: localhost
  username: root
  password:

development:
  adapter: mysql2
  encoding: utf8mb4
  database: NCKUOPEN_development
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8mb4
  database: NCKUOPEN_production
  host: localhost
  username: root
  password: root