version: "3.3"
services:
  frontend:
    image: docker-nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    container_name: frontend
    ports:
      - "4000:4000"
  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - db:/var/run/mysqld
    logging:
      driver: none
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -e production -b '0.0.0.0'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: nckuopen
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BUNDLE_PATH: /usr/local/bundle
    volumes:
      - ./backend:/rails-app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
volumes:
  db:
  bundle:
  redis:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     restart: on-failure
#     command: bundle exec rails s -p 3000 -e 
#     container_name: backend
#     environment:
#       DATABASE_URL: 'mysql2://db'
#       DB_USERNAME: 'root'
#       DB_PASSWORD: 'root'
#       DB_PORT: '3306'
#       DB_NAME: 'nckuopen'
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - redis
#   db:
#     platform: linux/x86_64
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'nckuopen'
#       MYSQL_ROOT_PASSWORD: 'root'
#       MYSQL_HOST: 'localhost'
#     expose:
#     # Opens port 3306 on the container
#       - '3306'
#     # Where our data will be persisted
#     volumes:
#       - 'my-db:/var/lib/mysql'
#     container_name: datab
#   redis:
#     image: redis:4.0-alpine
#     command: redis-server
#     volumes:
#       - redis:/data
#     ports:
#       - 6379
#     logging:
#       driver: none
# volumes:
#   my-db:
#   bundle:
#   redis: